source 'https://rubygems.org'

gem 'rails', '3.2.6'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'less-rails' # Need this for css in libs, unless we're not using any of those.
  gem 'stylus'
  gem 'therubyracer' # Needed to get around https://github.com/RailsApps/rails3-application-templates/issues/31
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

gem 'thin'
